spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(ZHIKqWxNdBRSv8wUqd96mjFWJugjNRlkBu7p18y4UEv93T9LqBuBFF1VY5NQywwk----------------)
    username: ENC(RsZO/TufVTVLG45qqDUfdQ==----------------)
    password: ENC(dfeBdGv+YW5enw0HmupELiLa0OQVExnJ----------------)
  redis:
    database: 0
    host: ENC(pn7ejuZmlyrvUoZ07neMVT8H54VeV+CT----------------)
    port: 8083
    password: ENC(HL3U6wYxEctA+TWkAD+mHnUB6YrhMw/X----------------)
    jedis:
      pool:
        max-active: 8
        max-idle: 200
        min-idle: 0
    timeout: 1000

server:
  port: 8082
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/example/EHMall/mapper/xml/**.xml

jasypt:
  encryptor:
    password: erp
